server:
  port: 7002
  servlet:
    context-path: /coupon-distribution

spring:
  application:
    name: eureka-client-coupon-distribution
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coupon_data?characterEncoding=UTF8&autoReconnect=true&serverTimezone=UTC
    username: coupon
    password: coupon
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocCouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: imooc-coupon-x
      auto-offset-reset: latest
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

logging:
  level:
    com.imooc.coupon: debug

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
      eureka-client-coupon-template:
        connectTimeout: 3000
        readTimeout: 5000
  circuitbreaker:
    enabled: true
